include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    unused_local_variable: ignore
    unnecessary_import: ignore

linter:
  rules:
    # Custom rules can be added here if needed