# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    deprecated_member_use: false
    use_build_context_synchronously: false
    unused_local_variable: false
    unnecessary_to_list_in_spreads: false
    curly_braces_in_flow_control_structures: false
    file_names: false
    non_constant_identifier_names: false
    prefer_final_fields: false
    annotate_overrides: false
    use_super_parameters: false
    unnecessary_import: false
    sort_child_properties_last: false