import '../../../../core/models/life_stage.dart';
import 'models/workout_exercise.dart';

class ClinicalWorkoutProtocols {
  static final Map<LifeStage, List<WorkoutRoutine>> routines = {
    LifeStage.teen: [
      const WorkoutRoutine(
        id: 'teen_routine_1',
        title: 'Athletic Foundation & Injury Prevention',
        goal: 'Growth plate safety, core stability, and athletic agility',
        targetStage: LifeStage.teen,
        durationMinutes: 35,
        estimatedCalories: 280,
        exercises: [
          WorkoutExercise(
            id: 't1',
            name: 'Bodyweight Goblet Squats',
            category: 'Strength',
            targetMuscles: 'Quadriceps, Glutes',
            sets: 3,
            reps: 12,
            instructions: 'Keep heels grounded, chest proud, knees tracking over toes.',
            mobilityModification: 'Squat to an elevated bench or chair for balance guidance.',
          ),
          WorkoutExercise(
            id: 't2',
            name: 'Push-Up to High Plank',
            category: 'Upper Body',
            targetMuscles: 'Pectorals, Anterior Deltoids, Core',
            sets: 3,
            reps: 10,
            instructions: 'Maintain a straight line from neck to heels. Avoid sagging lower back.',
            mobilityModification: 'Perform on an incline against a wall or sturdy table.',
          ),
          WorkoutExercise(
            id: 't3',
            name: 'Nordic Hamstring Curls (Assisted)',
            category: 'ACL Injury Prevention',
            targetMuscles: 'Hamstrings, Posterior Chain',
            sets: 3,
            reps: 6,
            instructions: 'Anchor feet under partner or couch, control eccentric descent.',
            mobilityModification: 'Use resistance bands around chest for descent support.',
          ),
        ],
      ),
    ],
    LifeStage.youngAdult: [
      const WorkoutRoutine(
        id: 'young_adult_routine_1',
        title: 'Peak Hypertrophy & Metabolic Conditioning',
        goal: 'Testosterone stimulation, muscular endurance, and VO2 Max',
        targetStage: LifeStage.youngAdult,
        durationMinutes: 45,
        estimatedCalories: 420,
        exercises: [
          WorkoutExercise(
            id: 'y1',
            name: 'Barbell Deadlifts (Conventional or Hex Bar)',
            category: 'Posterior Chain',
            targetMuscles: 'Erector Spinae, Glutes, Hamstrings, Lats',
            sets: 4,
            reps: 6,
            instructions: 'Hinge at the hips, brace core, push the floor away.',
            mobilityModification: 'Elevate bar on rack pulls or switch to Romanian Deadlifts with dumbbells.',
          ),
          WorkoutExercise(
            id: 'y2',
            name: 'Overhead Dumbbell Strict Press',
            category: 'Shoulder Strength',
            targetMuscles: 'Anterior/Medial Deltoids, Triceps, Upper Chest',
            sets: 3,
            reps: 8,
            instructions: 'Press straight overhead until biceps align with ears. Do not arch lower back.',
            mobilityModification: 'Seated neutral-grip dumbbell press to protect the shoulder capsule.',
          ),
          WorkoutExercise(
            id: 'y3',
            name: 'Zone 2 Metabolic Cardio (Assault Bike / Rowing)',
            category: 'Cardiorespiratory',
            targetMuscles: 'Full Body Cardiovascular Endurance',
            sets: 1,
            reps: 15,
            instructions: 'Maintain steady nasal breathing pace (heart rate 60–70% HR max).',
            mobilityModification: 'Brisk incline treadmill walking.',
          ),
        ],
      ),
    ],
    LifeStage.adult: [
      const WorkoutRoutine(
        id: 'adult_routine_1',
        title: 'Metabolic Health & Muscle Preservation',
        goal: 'Visceral fat reduction, insulin sensitivity, and joint integrity',
        targetStage: LifeStage.adult,
        durationMinutes: 40,
        estimatedCalories: 350,
        exercises: [
          WorkoutExercise(
            id: 'a1',
            name: 'Bulgarian Split Squats',
            category: 'Unilateral Lower Body',
            targetMuscles: 'Quadriceps, Gluteus Medius, Stabilizers',
            sets: 3,
            reps: 10,
            instructions: 'Place rear foot on bench, lower front thigh parallel to floor.',
            mobilityModification: 'Standard reverse lunges holding a wall for balance support.',
          ),
          WorkoutExercise(
            id: 'a2',
            name: 'Chest-Supported Dumbbell Rows',
            category: 'Postural Back Strength',
            targetMuscles: 'Rhomboids, Middle Trapezius, Latissimus Dorsi',
            sets: 3,
            reps: 12,
            instructions: 'Lie prone on incline bench, pull elbows toward hips without shrugging.',
            mobilityModification: 'Seated cable rows with resistance band.',
          ),
        ],
      ),
    ],
    LifeStage.midLife: [
      const WorkoutRoutine(
        id: 'midlife_routine_1',
        title: 'Cardiovascular Defense & Bone Mineral Density',
        goal: 'Arterial compliance, blood pressure regulation, and spinal stability',
        targetStage: LifeStage.midLife,
        durationMinutes: 35,
        estimatedCalories: 290,
        exercises: [
          WorkoutExercise(
            id: 'm1',
            name: 'Farmer\'s Walk (Heavy Carries)',
            category: 'Functional Core & Grip',
            targetMuscles: 'Forearms, Traps, Obliques, Cardiovascular System',
            sets: 4,
            reps: 40,
            instructions: 'Walk tall with proud chest, shoulders pulled down and back.',
            mobilityModification: 'Use moderate kettlebells or dumbbells with reduced distance.',
          ),
          WorkoutExercise(
            id: 'm2',
            name: 'Zone 2 Incline Walking or Cycling',
            category: 'Cardiovascular Longevity',
            targetMuscles: 'Heart, Vascular Endothelium',
            sets: 1,
            reps: 25,
            instructions: 'Maintain steady conversation pace to promote mitochondrial biogenesis.',
            mobilityModification: 'Recumbent bike with lumbar support.',
          ),
        ],
      ),
    ],
    LifeStage.olderAdult: [
      const WorkoutRoutine(
        id: 'older_adult_routine_1',
        title: 'Joint-Preserving Resistance & Postural Alignment',
        goal: 'Sarcopenia prevention, spinal decompression, and mobility maintenance',
        targetStage: LifeStage.olderAdult,
        durationMinutes: 30,
        estimatedCalories: 220,
        exercises: [
          WorkoutExercise(
            id: 'o1',
            name: 'Cable / Band Face Pulls',
            category: 'Rotator Cuff & Posture',
            targetMuscles: 'Posterior Deltoids, Infraspinatus, Upper Traps',
            sets: 3,
            reps: 15,
            instructions: 'Pull rope attachment toward bridge of nose, rotating hands back.',
            mobilityModification: 'Door-anchored light therapy bands.',
          ),
          WorkoutExercise(
            id: 'o2',
            name: 'Leg Press with Controlled Eccentric',
            category: 'Knee-Friendly Lower Body',
            targetMuscles: 'Quadriceps, Glutes',
            sets: 3,
            reps: 10,
            instructions: 'Keep feet flat on plate, descend for 3 seconds, press smoothly.',
            mobilityModification: 'Seated sit-to-stand from chair.',
          ),
        ],
      ),
    ],
    LifeStage.senior: [
      const WorkoutRoutine(
        id: 'senior_routine_1',
        title: 'Fall Prevention, Balance & Sarcopenia Defense',
        goal: 'Gait stability, proprioception, and independent mobility',
        targetStage: LifeStage.senior,
        durationMinutes: 25,
        estimatedCalories: 150,
        exercises: [
          WorkoutExercise(
            id: 's1',
            name: 'Chair Sit-to-Stand (Power Transition)',
            category: 'Functional Lower Body',
            targetMuscles: 'Quadriceps, Glutes, Hip Flexors',
            sets: 3,
            reps: 8,
            instructions: 'Stand up without using arms if able, gently lower back to chair.',
            mobilityModification: 'Use armrests or place hands on caregiver\'s forearms.',
          ),
          WorkoutExercise(
            id: 's2',
            name: 'Tandem Stance & Heel-to-Toe Walk (Supported)',
            category: 'Vestibular & Balance',
            targetMuscles: 'Ankle Stabilizers, Proprioceptors, Core',
            sets: 3,
            reps: 10,
            instructions: 'Place one foot directly in front of the other, alongside kitchen counter.',
            mobilityModification: 'Hold counter with both hands; practice single-leg balance for 10s.',
          ),
        ],
      ),
    ],
  };
}
